id: I555D4252
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1625
  ocr_info:
    timestamp: 03/21/23T14:10:34
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 22:25:43.898911+00:00
last_modified: 2024-02-28 22:25:43.898919+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1625
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1625
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྒྲོལ་མ་ཉེར་གཅིག་གི་བསྟོད་པ་བོད་རྒྱ་ཤན་སྦྱར་མ།
  languages:
  - zh
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.8734557979334099
  ocr_word_median_confidence_index: 0.96
bases:
  I3CN1629:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1629
      total_pages: 54
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1629.txt
    statistics:
      ocr_word_median_confidence_index: 0.96
      ocr_word_mean_confidence_index: 0.8734557979334099
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
